version: 2

project_name: dkron

env:
  # FIXME: PR to dkron to make it "sexy and forkable"
  - FOOBAR={{ if index .Env "FOOBAR"  }}{{ .Env.FOOBAR }}{{ else }}xtest{{ end }}

release:
  prerelease: auto

builds:
  - &xbuild
    main: .
    id: dkron
    binary: dkron
    env:
      - CGO_ENABLED=0
    goos:
      # - freebsd
      # - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - '7'
    ldflags:
      - -s -w -X github.com/distribworks/dkron/v4/dkron.Version={{.Version}} -X github.com/distribworks/dkron/v4/dkron.Codename=Abaniko

snapshot:
  version_template: "{{ .Tag }}-{{ .Env.FOOBAR }}-next"

dockers:
  # - image_templates:
  #     - fopina/{{ .ProjectName }}:{{ .Version }}-amd64
  #   dockerfile: Dockerfile.release
  #   use: buildx
  #   goos: linux
  #   goarch: amd64
  #   ids: &docker-ids
  #     - dkron
  #     - dkron-executor-rabbitmq
  #     - dkron-executor-nats
  #     - dkron-executor-kafka
  #     - dkron-executor-gcppubsub
  #     - dkron-executor-grpc
  #     - dkron-processor-files
  #     - dkron-processor-log
  #     - dkron-processor-syslog
  #     - dkron-processor-fluent
  #   build_flag_templates:
  #     - --platform=linux/amd64

  # - image_templates:
  #     - fopina/{{ .ProjectName }}:{{ .Version }}-arm64
  #   dockerfile: Dockerfile.release
  #   use: buildx
  #   goos: linux
  #   goarch: arm64
  #   ids: *docker-ids
  #   build_flag_templates:
  #     - --platform=linux/arm64/v8

  # - image_templates:
  #     - fopina/{{ .ProjectName }}:{{ .Version }}-armv7
  #   dockerfile: Dockerfile.release
  #   use: buildx
  #   goos: linux
  #   goarch: arm
  #   goarm: '7'
  #   ids: *docker-ids
  #   build_flag_templates:
  #     - --platform=linux/arm/v7

  - image_templates:
      - fopina/{{ .ProjectName }}:{{ .Version }}-light-amd64
    dockerfile: Dockerfile.release
    use: buildx
    goos: linux
    goarch: amd64
    ids: &docker-ids
      - dkron
    build_flag_templates:
      - --platform=linux/amd64

  - image_templates:
      - fopina/{{ .ProjectName }}:{{ .Version }}-light-arm64
    dockerfile: Dockerfile.release
    use: buildx
    goos: linux
    goarch: arm64
    ids: *docker-ids
    build_flag_templates:
      - --platform=linux/arm64/v8

  - image_templates:
      - fopina/{{ .ProjectName }}:{{ .Version }}-light-armv7
    dockerfile: Dockerfile.release
    use: buildx
    goos: linux
    goarch: arm
    goarm: '7'
    ids: *docker-ids
    build_flag_templates:
      - --platform=linux/arm/v7

docker_manifests:
#   - name_template: dkron/{{ .ProjectName }}:{{ .Version }}
#     image_templates:
#       - dkron/{{ .ProjectName }}:{{ .Version }}-amd64
#       - dkron/{{ .ProjectName }}:{{ .Version }}-arm64
#       - dkron/{{ .ProjectName }}:{{ .Version }}-armv7

#   - name_template: dkron/{{ .ProjectName }}:latest
#     image_templates:
#     - dkron/{{ .ProjectName }}:{{ .Version }}-amd64
#     - dkron/{{ .ProjectName }}:{{ .Version }}-arm64
#     - dkron/{{ .ProjectName }}:{{ .Version }}-armv7

  - name_template: fopina/{{ .ProjectName }}:{{ .Version }}-light
    image_templates:
    - fopina/{{ .ProjectName }}:{{ .Version }}-light-amd64
    - fopina/{{ .ProjectName }}:{{ .Version }}-light-arm64
    - fopina/{{ .ProjectName }}:{{ .Version }}-light-armv7

  - name_template: fopina/{{ .ProjectName }}:light
    image_templates:
    - fopina/{{ .ProjectName }}:{{ .Version }}-light-amd64
    - fopina/{{ .ProjectName }}:{{ .Version }}-light-arm64
    - fopina/{{ .ProjectName }}:{{ .Version }}-light-armv7

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^Merge pull request'