project_name: dkron

release:
  prerelease: auto

builds:
  - main: ./builtin/bins/dkron-executor-http/
    id: dkron-executor-http
    binary: dkron-executor-http
    env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

  - main: ./builtin/bins/dkron-executor-shell/
    id: dkron-executor-shell
    binary: dkron-executor-shell
    env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

  - main: ./builtin/bins/dkron-processor-files/
    id: dkron-processor-files
    binary: dkron-processor-files
    env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

  - main: ./builtin/bins/dkron-processor-log/
    id: dkron-processor-log
    binary: dkron-processor-log
    env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

  - main: ./builtin/bins/dkron-processor-syslog/
    id: dkron-processor-syslog
    binary: dkron-processor-syslog
    env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

  - main: .
    binary: dkron
    env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/distribworks/dkron/v2/dkron.Version={{.Version}}

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^Merge pull request'
