project_name: dkron

release:
  prerelease: auto

env:
  - IMAGE_PREFIX={{ if index .Env "IMAGE_PREFIX"  }}{{ .Env.IMAGE_PREFIX }}{{ else }}fopina{{ end }}

builds:
  - &xbuild
    main: .
    id: dkron
    binary: dkron
    env:
      - CGO_ENABLED=0
    goos:
      # - freebsd
      # - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - '7'
    ldflags:
      - -s -w -X github.com/distribworks/dkron/v4/dkron.Version={{.Version}} -X github.com/distribworks/dkron/v4/dkron.Codename=Abaniko

snapshot:
  name_template: "{{ .Tag }}-next"

dockers:
  - image_templates:
      - "{{ .Env.IMAGE_PREFIX }}/{{ .ProjectName }}:{{ .Version }}-light-amd64"
    dockerfile: Dockerfile.release
    use: buildx
    goos: linux
    goarch: amd64
    ids: &docker-ids
      - dkron
    build_flag_templates:
      - --platform=linux/amd64

  - image_templates:
      - "{{ .Env.IMAGE_PREFIX }}/{{ .ProjectName }}:{{ .Version }}-light-arm64"
    dockerfile: Dockerfile.release
    use: buildx
    goos: linux
    goarch: arm64
    ids: *docker-ids
    build_flag_templates:
      - --platform=linux/arm64/v8

  - image_templates:
      - "{{ .Env.IMAGE_PREFIX }}/{{ .ProjectName }}:{{ .Version }}-light-armv7"
    dockerfile: Dockerfile.release
    use: buildx
    goos: linux
    goarch: arm
    goarm: '7'
    ids: *docker-ids
    build_flag_templates:
      - --platform=linux/arm/v7

docker_manifests:
  - name_template: "{{ .Env.IMAGE_PREFIX }}/{{ .ProjectName }}:{{ .Version }}-light"
    image_templates:
    - "{{ .Env.IMAGE_PREFIX }}/{{ .ProjectName }}:{{ .Version }}-light-amd64"
    - "{{ .Env.IMAGE_PREFIX }}/{{ .ProjectName }}:{{ .Version }}-light-arm64"
    - "{{ .Env.IMAGE_PREFIX }}/{{ .ProjectName }}:{{ .Version }}-light-armv7"

  - name_template: "{{ .Env.IMAGE_PREFIX }}/{{ .ProjectName }}:light"
    image_templates:
    - "{{ .Env.IMAGE_PREFIX }}/{{ .ProjectName }}:{{ .Version }}-light-amd64"
    - "{{ .Env.IMAGE_PREFIX }}/{{ .ProjectName }}:{{ .Version }}-light-arm64"
    - "{{ .Env.IMAGE_PREFIX }}/{{ .ProjectName }}:{{ .Version }}-light-armv7"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^Merge pull request'